# ===============================
# SERVER
# ===============================
server.port=${PORT}

# ===============================
# DATASOURCE (FROM ENV)
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disable Open Session in View
spring.jpa.open-in-view=false

# ===============================
# SECURITY (TEMP ? JWT later)
# ===============================
spring.security.user.name=admin
spring.security.user.password=admin








groq.api.key=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


spring.data.redis.host=redis-19191.crce281.ap-south-1-3.ec2.cloud.redislabs.com
spring.data.redis.port=19191
spring.data.redis.username=default
spring.data.redis.password=AQfAT3yqTJp1ym5obGVpUKeTMrMZBcNp

spring.data.redis.timeout=60000
